### ISSUE TITLE
Test in README pointing to the wrong package.

### ISSUE THREAD

**Issue by TylerFeldhege** [intersystems-community/objectscript-docker-template#15]
The test listed in the README is pointing to ##class(dc.PackageSample.ObjectScript).Test() and the location is currently ##class(dc.sample.ObjectScript).Test().  

USER>w ##class(dc.PackageSample.ObjectScript).Test()
W ##CLASS(dc.PackageSample.ObjectScript).Test()
^
<CLASS DOES NOT EXIST> *dc.PackageSample.ObjectScript

USER>w ##class(dc.sample.ObjectScript).Test()
It works!
42

**Comment by evshvarov** [comment]
fixed! Thank you!
