### ISSUE TITLE
module.xml version tag not correctly closed

### ISSUE THREAD

**Issue by marceldenouden** [intersystems-community/objectscript-docker-template#4]
Hi, 

I think there is an error in module.xml. The version tag is not closed correctly:
`<Version>1.1.1/Version>`
should be:
`<Version>1.1.1</Version>`

I changed it manually and it worked.

Other small issue in the README.md. It says you can test with:
write ##class(PackageSample.ObjectScript).Test()

but I think this should be:

##class(**dc**.PackageSample.ObjectScript).Test()

**Comment by evshvarov** [comment]
Hi Marcel!
thank you, fixed!
