### ISSUE TITLE
ERROR: Service 'iris' failed to build : no space left on device

### ISSUE THREAD

**Issue by drechema** [intersystems-community/objectscript-docker-template#5]
Just git clone and docker-compose build I get this error:
ERROR: Service 'iris' failed to build : Error processing tar file(exit status 1): write /usr/irissys/mgr/IRIS.DAT: no space left on device

**Comment by evshvarov** [comment]
It's because there is no space in your docker left.
Run 
```
docker system prune -f
```
to clean up. 
Other useful commands are [listed here](https://github.com/intersystems-community/objectscript-docker-template/blob/master/dev.md).

**Comment by evshvarov** [comment]
Or increase the space in docker settings

**Comment by drechema** [comment]
Perfect!! Thanks
